### ISSUE TITLE
error when invoking NewOrder on main

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1302] opened 2020-11-06 22:19 UTC
# error when invoking NewOrder on main

## Summary
error when invoking NewOrder on main on jenkins: http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/764/pipeline#step-491-log-175

## Environment
End to end performance on jenkins

**OS**: Ubuntu 20.04

**Compiler**: Clang 8

**Comment by mbutrovich** [comment] 2020-11-06 22:25
Dupe of #1128.

**Closed by mbutrovich** 2020-11-06 22:25 UTC
Labels: bug, tests
