### ISSUE TITLE
jumbotest_messenger_messenger_test timesout on jenkins

### ISSUE THREAD

**Issue by eppingere** [cmu-db/noisepage#1319] opened 2020-11-10 13:26 UTC
# jumbotest_messenger_messenger_test timesout on jenkins

## Summary
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/791/tests
It seems that the test times out. Potentially due to deadlock or other hangup.

## Environment

**OS**: Ubuntu 20.04 (LTS)

**Compiler**: GCC 9.3 release

**Comment by crd477** [comment] 2020-11-10 13:42
I think there is no output only because the test was terminated by `timeout` because it ran too long.

**Comment by eppingere** [comment] 2020-11-10 15:17
Wait did it? It took 50 mins and the timeout is an hour? Is the timeout short?

**Comment by crd477** [comment] 2020-11-10 15:30
There appears to be a discrepancy between the Jenkins stage designation and the actual ctest invocation.  The enforced timeout is apparently 3000 seconds.  See the full pipeline stage results here:
http://jenkins.db.cs.cmu.edu:8080/blue/rest/organizations/jenkins/pipelines/terrier/branches/master/runs/791/nodes/47/log/?start=0

Specifically:
```
[0/1] cd /jenkins/workspace/terrier_master@3/build && ctest --resource-spec-file /jenkins/workspace/terrier_master@3/build-support/data/ctest_resource_specs.json -j 24 -L jumbotests --no-compress-output -T Test --timeout 3000
[...]
37/40 Test #162: jumbotest_messenger_messenger_test ...............***Timeout 3000.08 sec
[...]
```

**Comment by eppingere** [comment] 2020-11-10 15:43
Hmmmm ok i will update to be about the test timing out

**Comment by lmwnshn** [comment] 2020-11-10 20:06
I've been trying to debug this and haven't been able to reproduce it locally. It happened before too.

**Comment by lmwnshn** [comment] 2020-12-11 21:55
Today: it appears that sometimes this happens when there's a lingering port and it fails to bind one of the replicas.

**Comment by lmwnshn** [comment] 2020-12-29 18:57
In retrospect, I am dumb and there is a race condition especially in `BasicListenTest` where B tries to send before A is ready. Will be fixed in an upcoming PR that adds a `spin_until_init()` to each forked process + sets some ZeroMQ flags to only queue on completed connections + switch from indefinite send/recv blocking to a 1s timeout.

**Comment by lmwnshn** [comment] 2020-12-29 18:58
In general, the state of testing forked processes seems to be sad.

**Comment by lmwnshn** [comment] 2021-01-03 20:33
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/847/pipeline/ Testing forked processes sucks.

**Comment by malin1993ml** [comment] 2021-03-11 20:30
Unfortunately, this shows up again:(
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-1509/23/pipeline

**Comment by lmwnshn** [comment] 2021-05-24 22:21
This test no longer exists.

**Closed by lmwnshn** 2021-05-24 22:21 UTC
Labels: bug, infrastructure, tests
