### ISSUE TITLE
psql show command

### ISSUE THREAD

**Issue by Ethan-DB** [cmu-db/noisepage#1485] opened 2021-02-21 13:31 UTC
# Bug Report
## Summary
The results of the command `show`  is not the same as PostgreSQL. It should give the cost, not transaction_isolation.
```SQL
noisepage=# show cpu_tuple_cost;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)

noisepage=# show seq_page_cost;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)

noisepage=# show cpu_operator_cost;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)
```

**Comment by Ethan-DB** [comment] 2021-02-21 13:36
```SQL
test=# show block_size;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)
```

**Comment by Ethan-DB** [comment] 2021-02-22 02:19
```sql
noisepage=# show xxx;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)

noisepage=# show transaction isolation level;
 transaction_isolation 
-----------------------
 snapshot isolation
(1 row)
```

**Comment by lmwnshn** [comment] 2021-02-22 03:09
Hi, would you like to work on it? Duplicate of #1188. Glad you like my capybara picture.

**Closed by lmwnshn** 2021-02-22 03:09 UTC

**Comment by Ethan-DB** [comment] 2021-02-22 03:23
> Hi, would you like to work on it? Duplicate of #1188. Glad you like my capybara picture.

It is so cute. May I use it? If not, I will replace it. :)

**Comment by lmwnshn** [comment] 2021-02-22 03:42
Go ahead! I like capybaras. :)
